/**
 * Auto-Documentation System
 * Automatically generates build reports after successful builds
 * STREAM E - Oct 23, 2025
 */

import { promises as fs } from 'fs';
import path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

export interface BuildTask {
  id: string;
  description: string;
  status: 'completed' | 'pending' | 'failed';
  architectApproved?: boolean;
  evidence?: string[];
}

export interface BuildData {
  projectId: number;
  projectName?: string;
  agent: string;
  executionMode: 'FOCUSED' | 'PARALLEL' | 'SIMULTANEOUS';
  summary: string;
  reasoning?: string;
  tasks: BuildTask[];
  screenshots?: string[];
  codeChanges?: string[];
  nextSteps?: string[];
  timestamp?: Date;
}

export interface IntegrationStatus {
  feature: string;
  status: 'planned' | 'in_progress' | 'completed' | 'blocked';
  completedAt?: Date;
  buildReportLink?: string;
}

/**
 * Generate a markdown build report from build data
 */
export function generateBuildReport(buildData: BuildData): string {
  const timestamp = buildData.timestamp || new Date();
  const dateStr = timestamp.toISOString().split('T')[0];
  const timeStr = timestamp.toTimeString().split(' ')[0];
  
  const report = `# Build Report - ${buildData.projectName || `Project ${buildData.projectId}`}

**Build Date:** ${dateStr} ${timeStr}  
**Agent:** ${buildData.agent}  
**Project ID:** ${buildData.projectId}  
**Execution Mode:** ${buildData.executionMode}

---

## Summary

### What Was Built
${buildData.summary}

${buildData.reasoning ? `### Why
${buildData.reasoning}
` : ''}

---

## Tasks Completed

${buildData.tasks.map((task, idx) => `### ${idx + 1}. ${task.description}

- **Status:** ${task.status === 'completed' ? '✅' : task.status === 'failed' ? '❌' : '⏳'} ${task.status}
- **Architect Approved:** ${task.architectApproved ? '✅ Yes' : '⏳ Pending'}
${task.evidence && task.evidence.length > 0 ? `- **Evidence:** 
${task.evidence.map(e => `  - ${e}`).join('\n')}` : ''}
`).join('\n')}

---

## Evidence

${buildData.screenshots && buildData.screenshots.length > 0 ? `### Screenshots
${buildData.screenshots.map((screenshot, idx) => `${idx + 1}. [Screenshot ${idx + 1}](${screenshot})`).join('\n')}
` : '_No screenshots available_'}

${buildData.codeChanges && buildData.codeChanges.length > 0 ? `### Code Changes
${buildData.codeChanges.map((change, idx) => `${idx + 1}. \`${change}\``).join('\n')}
` : '_No code changes tracked_'}

---

## Next Steps

${buildData.nextSteps && buildData.nextSteps.length > 0 ? buildData.nextSteps.map((step, idx) => `${idx + 1}. ${step}`).join('\n') : '_No follow-up work identified_'}

---

## Integration Checklist

- [${buildData.tasks.some(t => t.description.toLowerCase().includes('component built')) ? 'x' : ' '}] Component built
- [${buildData.tasks.some(t => t.description.toLowerCase().includes('import')) ? 'x' : ' '}] Component imported in parent
- [${buildData.tasks.some(t => t.description.toLowerCase().includes('render')) ? 'x' : ' '}] Component rendered in JSX
- [${buildData.tasks.some(t => t.description.toLowerCase().includes('props')) ? 'x' : ' '}] Props passed correctly
- [${buildData.tasks.some(t => t.description.toLowerCase().includes('event')) ? 'x' : ' '}] Event handlers wired
- [${buildData.tasks.some(t => t.description.toLowerCase().includes('backend') || t.description.toLowerCase().includes('api')) ? 'x' : ' '}] Backend endpoints exist (if needed)
- [${buildData.tasks.some(t => t.description.toLowerCase().includes('test') || t.description.toLowerCase().includes('journey')) ? 'x' : ' '}] User journey tested end-to-end
- [${buildData.screenshots && buildData.screenshots.length > 0 ? 'x' : ' '}] Screenshot taken showing feature

---

_Auto-generated by Build Documentation System - STREAM E_
`;

  return report;
}

/**
 * Save build report to docs/BUILD_REPORTS/ directory
 */
export async function saveBuildReport(
  projectId: number,
  report: string
): Promise<string> {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const filename = `${projectId}_${timestamp}.md`;
  const filePath = path.join(process.cwd(), 'docs', 'BUILD_REPORTS', filename);

  // Ensure directory exists
  const dirPath = path.join(process.cwd(), 'docs', 'BUILD_REPORTS');
  await fs.mkdir(dirPath, { recursive: true });

  // Write report
  await fs.writeFile(filePath, report, 'utf-8');

  console.log(`[Auto-Documentation] Build report saved: ${filePath}`);
  return filePath;
}

/**
 * Update integration status tracking
 * Maintains a INTEGRATION_STATUS.md file tracking all features
 */
export async function updateIntegrationStatus(
  feature: string,
  status: IntegrationStatus['status'],
  buildReportPath?: string
): Promise<void> {
  const statusFilePath = path.join(
    process.cwd(),
    'docs',
    'BUILD_REPORTS',
    'INTEGRATION_STATUS.md'
  );

  let content = '';
  
  // Read existing file if it exists
  try {
    content = await fs.readFile(statusFilePath, 'utf-8');
  } catch (error) {
    // File doesn't exist, create header
    content = `# Integration Status Tracker

Last Updated: ${new Date().toISOString()}

| Feature | Status | Completed At | Build Report |
|---------|--------|--------------|--------------|
`;
  }

  // Parse existing table
  const lines = content.split('\n');
  const headerEndIndex = lines.findIndex(line => line.startsWith('|---'));
  
  if (headerEndIndex === -1) {
    throw new Error('Invalid INTEGRATION_STATUS.md format');
  }

  const tableRows = lines.slice(headerEndIndex + 1).filter(line => line.trim().startsWith('|'));
  
  // Find or create row for this feature
  const existingRowIndex = tableRows.findIndex(row => 
    row.toLowerCase().includes(feature.toLowerCase())
  );

  const statusEmoji = {
    planned: '📋',
    in_progress: '🔄',
    completed: '✅',
    blocked: '🚫'
  }[status] || '❓';

  const completedAt = status === 'completed' ? new Date().toISOString().split('T')[0] : '-';
  const reportLink = buildReportPath 
    ? `[Report](${path.basename(buildReportPath)})`
    : '-';

  const newRow = `| ${feature} | ${statusEmoji} ${status} | ${completedAt} | ${reportLink} |`;

  if (existingRowIndex >= 0) {
    tableRows[existingRowIndex] = newRow;
  } else {
    tableRows.push(newRow);
  }

  // Reconstruct file
  const header = lines.slice(0, headerEndIndex + 1);
  const newContent = [
    ...header,
    ...tableRows,
    '',
    `_Last updated: ${new Date().toISOString()}_`
  ].join('\n');

  await fs.writeFile(statusFilePath, newContent, 'utf-8');
  console.log(`[Auto-Documentation] Integration status updated: ${feature} → ${status}`);
}

/**
 * Create Git commit for documentation updates (optional)
 * Only works if Git is initialized and user has permissions
 */
export async function gitCommitDocs(message: string): Promise<boolean> {
  try {
    // Check if git is initialized
    await execAsync('git rev-parse --git-dir');

    // Stage all files in docs/BUILD_REPORTS/
    await execAsync('git add docs/BUILD_REPORTS/');

    // Commit with provided message
    const { stdout } = await execAsync(`git commit -m "${message}"`);
    
    console.log(`[Auto-Documentation] Git commit created: ${stdout.trim()}`);
    return true;
  } catch (error: any) {
    // Git not available or no changes to commit
    console.log(`[Auto-Documentation] Git commit skipped: ${error.message}`);
    return false;
  }
}

/**
 * High-level function to generate and save a complete build report
 */
export async function createBuildReport(
  buildData: BuildData,
  options?: {
    updateStatus?: boolean;
    gitCommit?: boolean;
  }
): Promise<{ filePath: string; report: string }> {
  // Generate report
  const report = generateBuildReport(buildData);
  
  // Save to file
  const filePath = await saveBuildReport(buildData.projectId, report);
  
  // Update integration status if requested
  if (options?.updateStatus && buildData.summary) {
    await updateIntegrationStatus(
      buildData.summary.substring(0, 50), // Use first 50 chars as feature name
      buildData.tasks.every(t => t.status === 'completed') ? 'completed' : 'in_progress',
      filePath
    );
  }
  
  // Git commit if requested
  if (options?.gitCommit) {
    await gitCommitDocs(
      `docs: Build report for project ${buildData.projectId} - ${buildData.summary.substring(0, 50)}`
    );
  }
  
  return { filePath, report };
}
