groups:
  # ==========================================
  # Application Performance Alerts
  # ==========================================
  - name: application
    interval: 15s
    rules:
      - alert: HighAPILatency
        expr: histogram_quantile(0.95, rate(http_request_duration_ms_bucket[5m])) > 500
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High API latency detected"
          description: "95th percentile latency is {{ $value | humanize }}ms (threshold: 500ms)"

      - alert: CriticalAPILatency
        expr: histogram_quantile(0.99, rate(http_request_duration_ms_bucket[5m])) > 2000
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: "Critical API latency detected"
          description: "99th percentile latency is {{ $value | humanize }}ms (threshold: 2000ms)"

      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} (threshold: 5%)"

      - alert: LowCacheHitRate
        expr: sum(rate(cache_hits_total[5m])) / (sum(rate(cache_hits_total[5m])) + sum(rate(cache_misses_total[5m]))) < 0.60
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is {{ $value | humanizePercentage }} (threshold: 60%)"

      - alert: AgentFixSuccessRateLow
        expr: sum(rate(agent_fixes_total{success="true"}[5m])) / sum(rate(agent_fixes_total[5m])) < 0.75
        for: 10m
        labels:
          severity: high
        annotations:
          summary: "Agent auto-fix success rate dropped"
          description: "Success rate is {{ $value | humanizePercentage }} (threshold: 75%)"

  # ==========================================
  # Infrastructure Alerts
  # ==========================================
  - name: infrastructure
    interval: 30s
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service has been down for more than 2 minutes"

      - alert: HighMemoryUsage
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 15
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Available memory is {{ $value | humanize }}% (threshold: 15%)"

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value | humanize }}% (threshold: 85%)"

  # ==========================================
  # Database Alerts
  # ==========================================
  - name: database
    interval: 30s
    rules:
      - alert: SlowDatabaseQueries
        expr: avg_over_time(db_query_duration_ms{quantile="0.95"}[5m]) > 250
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow database queries detected"
          description: "95th percentile query time is {{ $value | humanize }}ms (threshold: 250ms)"

      - alert: DatabaseConnectionPoolExhausted
        expr: db_connections_active / db_connections_max > 0.8
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Database connection pool nearly exhausted"
          description: "{{ $value | humanizePercentage }} of connections in use (threshold: 80%)"
